description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.18350863564909967
  joint_2: 0.7929221244308463
  joint_3: 2.6709624698266783
  joint_4: -0.26469106676835175
  joint_5: 0.51472082201002
  joint_6: -1.3190629705282995
