description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 1.124679585011554
  joint_2: 0.8245771817823797
  joint_3: 2.611438728458335
  joint_4: 0.5079657418486457
  joint_5: 2.1961664401250713
  joint_6: -0.8234260682433078
