description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.30616073992472453
  joint_2: 1.7239754629990933
  joint_3: 2.6995883682466526
  joint_4: -1.4335968467579443
  joint_5: 1.818486396807466
  joint_6: -1.2185240014065566
