description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.41154644243317423
  joint_2: 2.7194901804689304
  joint_3: -0.30082937274745286
  joint_4: 0.5042398206188307
  joint_5: 0.799768089906329
  joint_6: 0.1922327218467956
