description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.12507546155276258
  joint_2: 2.7586272875001168
  joint_3: -0.2898636810684045
  joint_4: 0.5323204448190173
  joint_5: 1.3667424684586906
  joint_6: -0.358777856555931
