description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.22437248831861942
  joint_2: 2.723064726614866
  joint_3: -0.25363450860762643
  joint_4: 0.45304641697172693
  joint_5: 0.15797252717369198
  joint_6: 0.7986472589170056
