description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.7315203376700155
  joint_2: 1.7784405119649216
  joint_3: 2.6658734948744147
  joint_4: -1.430507122726888
  joint_5: 1.4286592845544233
  joint_6: -1.1853240067097692
