description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.21525459714717288
  joint_2: 2.7666547243941455
  joint_3: -0.2545432675865531
  joint_4: 0.44489788754356696
  joint_5: 0.09726745563003825
  joint_6: 0.38813076215904635
