description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.4609223281224247
  joint_2: 2.764049521159065
  joint_3: -0.3105227830235725
  joint_4: 0.3042220541030143
  joint_5: 0.8840100001717518
  joint_6: -0.49124457663639515
