description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.7859549534266438
  joint_2: 1.7231576834964322
  joint_3: 0.7465754353380181
  joint_4: -0.4599529852115696
  joint_5: 0.7609338083726278
  joint_6: -0.11232255329804086
