description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.45301613442197847
  joint_2: 2.762080703447058
  joint_3: -0.30879615037982755
  joint_4: 0.35971691691703755
  joint_5: 0.9084859086708431
  joint_6: 0.36713843916205624
