description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.708195542709996
  joint_2: 1.762385638176864
  joint_3: 1.6759627063620173
  joint_4: -0.4385062733089004
  joint_5: 2.2480262858558193
  joint_6: -0.05028463996006922
