description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.3262745864925365
  joint_2: 0.7194338338340751
  joint_3: 0.7175859956616104
  joint_4: 0.5325022154472341
  joint_5: 0.8591706257459526
  joint_6: 0.8870695169827854
