description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.46273984608027796
  joint_2: 2.741633504010404
  joint_3: -0.31015927943200183
  joint_4: 0.4997263271063773
  joint_5: -0.03741055913338273
  joint_6: 3.066817768052543
