description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.38040630142195403
  joint_2: 2.788101398631952
  joint_3: -0.30555490060544005
  joint_4: 0.39431032321574766
  joint_5: 0.1279531983193637
  joint_6: 0.0876951943853441
