description: 'Home calibration: arm fully extended upward'
joint_offsets:
  joint_1: 0.4364767021730818
  joint_2: 1.7810152819908018
  joint_3: 2.6697809984081324
  joint_4: 0.5311996514945568
  joint_5: -0.1816305337593179
  joint_6: -1.506297565072077
